### ISSUE TITLE
Update fails with curl error CRYPT_E_REVOCATION_OFFLINE (0x80092013)

### ISSUE THREAD

**Issue by Tmp341** [fonic/ipfilter#8] opened 2024-08-04 11:09 UTC
**Version / Release:**
IPFilter v4.4

**Platform / OS:**
Windows 10 Home 64-bit (10.0, Build 19045), Ubuntu 22.04.1 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64), Git for Windows v2.45.2

**Bug description:**
Update starts, then script closes itself.

**Steps to reproduce:**
I'm not doing any special steps. Just double clicking on my script file. But it seems this error is being logged since the start of July.

**Console output:**
```
--------------- Started: Sun Aug  4 13:29:20 TSS 2024 ---------------
Downloading I-BlockList blocklists...
Downloading blocklist 'Pedophiles'...
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
An error occured while updating, aborting.
```
**Solution:**
I was creating this issue, but i also found a solution for this. Adding ``"--ssl-no-revoke"`` at this line fixes the problem:
https://github.com/fonic/ipfilter/blob/e22359f0175457cb865fcbde12606fe688ac07de/ipfilter.conf#L43

**Comment by fonic** [comment] 2024-08-04 11:44
Thank you for reporting this.

That error indicates that `curl` fails to verify whether the connection to I-Blocklist (via URL https://list.iblocklist.com/) actually is secure or not.

Even though adding `--ssl-no-revoke` to `CURL_OPTS` in `ipfilter.conf` might be a quick and tempting workaround (*), the real question is **_why_** does this check fail. Could be that your connection is somehow partially blocked (e.g. by a firewall or even malware), could be that I-BlockList changed something on their end.

**I'm currently unable to reproduce the error**, thus we'll have to wait and see if there are other users with the same issue.

---

(*) **Be aware that using option `--ssl-no-revoke` significantly lessens your security:**

```
--ssl-no-revoke
    (TLS) (Schannel) Disable certificate revocation checks. WARNING: this option loosens the
    SSL security, and by using this flag you ask for exactly that.
```

For that very reason, I'll reject the pull request.

**Comment by Tmp341** [comment] 2024-08-05 15:19
Well, i know removing SSL check is harmful, but i somehow couldn't pass an invisible block without this. I can open I-Blocklist site on my browsers. I should check other methods to see if my IP partially blocked to use via this automated script.

**Comment by fonic** [comment] 2024-08-05 17:51
We'll leave this open for now, in case other users with the same issue come here looking for answers.

**Comment by fonic** [comment] 2024-08-06 09:58
> Well, i know removing SSL check is harmful, but i somehow couldn't pass an invisible block without this. I can open I-Blocklist site on my browsers. I should check other methods to see if my IP partially blocked to use via this automated script.

What happens when you open https://list.iblocklist.com/ (this exact URL) in a browser?

**Comment by Tmp341** [comment] 2024-08-06 18:29
> What happens when you open https://list.iblocklist.com/ (this exact URL) in a browser?

Leads me to [https://list.iblocklist.com/humantest?](https://list.iblocklist.com/humantest?).
And completing the test leads me to [https://list.iblocklist.com/?](https://list.iblocklist.com/?), which shows:
``Bad request;
list unavailable``

**Comment by fonic** [comment] 2024-08-06 18:32
> > What happens when you open https://list.iblocklist.com/ (this exact URL) in a browser?
>
> Leads me to https://list.iblocklist.com/humantest

That might be the cause. Maybe they're doing some redirection stuff that `curl` doesn't like.

You could try to solve the captcha and then run the script again without `--ssl-no-revoke` (both from the same machine) and check if that changes anything.

**Comment by Tmp341** [comment] 2024-08-07 06:13
> That might be the cause. Maybe they're doing some redirection stuff that `curl` doesn't like.
> 
> You could try to solve the captcha and then run the script again without `--ssl-no-revoke` (both from the same machine) and check if that changes anything.

Tried again with this method. First try, no problem:
```
"IP filter successfully updated."
```

**Comment by fonic** [comment] 2024-08-07 07:13
> Tried again with this method. First try, no problem:
> 
> ```
> "IP filter successfully updated."
> ```

So just to make sure: you solved the captcha, then ran the script **without** `--ssl-no-revoke` and it worked?

That would indicate that I-BlockList is using some sort of IP-based blocking with redirection to captcha.

**Comment by Tmp341** [comment] 2024-08-07 18:35
> So just to make sure: you solved the captcha, then ran the script **without** `--ssl-no-revoke` and it worked?
> 
> That would indicate that I-BlockList is using some sort of IP-based blocking or redirection to captcha.

At the time of my testing, yes, solved captcha on browser, and i could make script work without the parameter.

**Comment by fonic** [comment] 2024-08-08 12:49
> At the time of my testing, yes, solved captcha on browser, and i could make script work without the parameter.

Ok, good. Then let's see what happens as time goes on. Let me know if it keeps working or stops working again at some point.

**Comment by Tmp341** [comment] 2024-08-12 06:19
> Ok, good. Then let's see what happens as time goes on. Let me know if it keeps working or stops working again at some point.

Tried again today. Worked without an error (same method, open on browser first, then download). I will try again without doing captcha in a couple of days, to see if it works or not.

**Comment by Tmp341** [comment] 2024-08-17 11:48
Tried again today. Didn't open the browser to verify captcha. No problem occured, worked normally.

**Comment by fonic** [comment] 2024-08-17 13:04
> Tried again today. Didn't open the browser to verify captcha. No problem occured, worked normally.

I investigated this a bit further and it would seem I-BlockList is moving towards restricting/preventing downloads by unregistered users. However, registered users (registration is free) are allowed to download lists without restrictions (i.e. no captcha).

**I'll add support for this in an upcoming version.**

**Closed as completed** 2024-08-18 10:08 UTC

**Comment by fonic** [comment] 2024-08-18 10:33
Fixed in release [ipfilter-v4.5](https://github.com/fonic/ipfilter/releases/tag/ipfilter-v4.5).

**Comment by Tmp341** [comment] 2024-09-11 09:34
Same error occured even after solving captcha:

```log
--------------- Started: Wed Sep 11 12:31:13 TSS 2024 ---------------
Downloading I-BlockList blocklists...
Downloading blocklist 'Pedophiles'...
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
An error occured while updating, aborting.
--------------- Ended: Wed Sep 11 12:31:29 TSS 2024 ---------------
```

**Comment by fonic** [comment] 2024-09-11 09:41
Try [ipfilter-v4.5](https://github.com/fonic/ipfilter/releases/tag/ipfilter-v4.5) then.

It is also still a possibility that you have a totally different issue at hand with your machine or Internet connection. I haven't been able to reproduce this error of yours, no matter what I try. Also, no one else has reported it thus far.

**Comment by Tmp341** [comment] 2024-09-11 09:43
> Try [ipfilter-v4.5](https://github.com/fonic/ipfilter/releases/tag/ipfilter-v4.5) then.
> 
> It is also still a possibility that you have a totally different issue at hand with your machine or Internet connection. I haven't been able to reproduce this error of yours, no matter what I try. Also, no one else has reported it thus far.

Been using that since it's release. Maybe an error with location or something.

Thank you for the answer.

**Comment by fonic** [comment] 2024-09-11 09:52
> Been using that since it's release. Maybe an error with location or something.

Oh, I didn't know that. Then it is something else _for sure_.

There is one thing you could try:

https://github.com/fonic/ipfilter/blob/84f4c806b3d9acdefa7175c5c2c22c580b8d26e4/ipfilter.sh#L168-L170

Edit the file and change `is_cmd_avail "curl"` to `is_cmd_avail "curlx"`. IP-Filter will then try to use `wget` instead of `curl` for file downloads. See if that changes things.

**Comment by Tmp341** [comment] 2024-09-11 10:01
> Oh, I didn't know that. Then it is something else _for sure_.
> 
> There is one thing you could try:
> 
> https://github.com/fonic/ipfilter/blob/84f4c806b3d9acdefa7175c5c2c22c580b8d26e4/ipfilter.sh#L168-L170
> 
> Edit the file and change `is_cmd_avail "curl"` to `is_cmd_avail "curlx"`. IP-Filter will then try to use `wget` instead of `curl` for file downloads. See if that changes things.

Can Windows be the problem here? I've listed apps i have at first comment. But, i can give more details. 

I telling this because i've found this on an old Stackoverflow thread:
`
This is not about programming or development thus offtopic, but: you are using the Windows port of curl, probably from CMD although you didn't say, and in CMD (for most things) singlequotes don't work like a Unix shell, but doublequotes do.
`

**Comment by Tmp341** [comment] 2024-09-11 10:04
Tried it:

```
--------------- Started: Wed Sep 11 13:02:20 TSS 2024 ---------------
Downloading I-BlockList blocklists...
Downloading blocklist 'Pedophiles'...
Unable to download 'https://list.iblocklist.com/?list=dufcxgnbjsdwmwctgfuj&fileformat=p2p&archiveformat=gz&username=Nnv387&pin=353952': no download command available
An error occured while updating, aborting.
--------------- Ended: Wed Sep 11 13:02:20 TSS 2024 ---------------
```

**Comment by Tmp341** [comment] 2024-09-11 10:50
Tried it:

```
--------------- Started: Wed Sep 11 13:02:20 TSS 2024 ---------------
Downloading I-BlockList blocklists...
Downloading blocklist 'Pedophiles'...
Unable to download 'https://list.iblocklist.com/?list=dufcxgnbjsdwmwctgfuj&fileformat=p2p&archiveformat=gz&username=******&pin=******': no download command available
An error occured while updating, aborting.
--------------- Ended: Wed Sep 11 13:02:20 TSS 2024 ---------------
```

Tried to use curl directly:

```
curl -v https://list.iblocklist.com/?
* Host list.iblocklist.com:443 was resolved.
* IPv6: (none)
* IPv4: 54.175.167.220
*   Trying 54.175.167.220:443...
* Connected to list.iblocklist.com (54.175.167.220) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
* Closing connection
* schannel: shutting down SSL/TLS connection with list.iblocklist.com port 443
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_REVOCATION_OFFLINE (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
```

**Comment by fonic** [comment] 2024-09-11 10:56
> Tried it:

Well, you need to have `wget` installed for this to work, of course. The error tells me that you currently don't.

**Comment by fonic** [comment] 2024-09-11 10:59
> Tried it:

Well, you need to have `wget` installed for this to work, of course. The error tells me that you currently don't.

> Can Windows be the problem here? I've listed apps i have at first comment. But, i can give more details.

It could be, but the weird thing is that it seems to sometimes to work for you, but other times you get the error. This indicates a problem related to your Internet connection or ISP.

> I telling this because i've found this on an old Stackoverflow thread: `This is not about programming or development thus offtopic, but: you are using the Windows port of curl, probably from CMD although you didn't say, and in CMD (for most things) singlequotes don't work like a Unix shell, but doublequotes do.`

Not related to the error you are experiencing.

**Comment by Tmp341** [comment] 2024-09-11 11:02
> > Can Windows be the problem here? I've listed apps i have at first comment. But, i can give more details.
> 
> It could be, but the weird thing is that it seems to sometimes to work for you, but other times you get the error. This indicates a problem related to your Internet connection or ISP.

Well, if i use "--ssl-no-revoke", it works without problem.

**Comment by fonic** [comment] 2024-09-11 11:05
Could you post the output of `curl --version`?

**Comment by Tmp341** [comment] 2024-09-11 11:11
```
curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-03-27
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```

**Comment by fonic** [comment] 2024-09-11 13:36
> ```
> curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
> Release-Date: 2024-03-27
> Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
> Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
> ```

Now that explains it. Microsoft apparently ships a [forked/modified version of `curl`](https://curl.se/windows/microsoft.html), which uses Windows' _Schannel_ backend to validate certificates, which is known to cause several issues (there are countless reports on that topic).

Try installing and using a version of `curl` (the latest one is 8.10.0) that has not been tampered with by the redmondian devils or switch to `wget` as mentioned above.

**Comment by Tmp341** [comment] 2024-09-11 14:11
> Now that explains it. Microsoft apparently ships a [forked/modified version of `curl`](https://curl.se/windows/microsoft.html), which uses Windows' _Schannel_ backend to validate certificates, which is known to cause several issues (there are countless reports on that topic).
> 
> Try installing and using a version of `curl` (the latest one is 8.10.0) that has not been tampered with by the redmondian devils or switch to `wget` as mentioned above.

I've installed curl via winget and added it to user environments. But cmd/powershell/bash still refuse to use it (use 8.7.1 instead) and i couldn't figure out how to update it (tried manually change but Windows blocked it, gotta change via Safe Mode etc it seems).

Do you know a fast way to reroute your curl commands to my manual curl route?

**Comment by Tmp341** [comment] 2024-09-11 15:05
> Now that explains it. Microsoft apparently ships a [forked/modified version of `curl`](https://curl.se/windows/microsoft.html), which uses Windows' _Schannel_ backend to validate certificates, which is known to cause several issues (there are countless reports on that topic).
> 
> Try installing and using a version of `curl` (the latest one is 8.10.0) that has not been tampered with by the redmondian devils or switch to `wget` as mentioned above.

I already had Cygwin. After running it's installer again, i've downloaded these packages:

- curl
- wget
- unzip

After changing directory to where the files were, i could run it through cygwin and finished without issue.

**Comment by fonic** [comment] 2024-09-16 09:50
Sounds good. Let me know if that finally solves your issues.
